### ISSUE TITLE
Create a guide on how to run the relayer, including the unsafe rpc node

### ISSUE THREAD

**Issue by blasrodri** [ComposableFi/centauri#283]
The configuration file for Picasso in Kusama, and Composable in Polkadot is

```toml
[chain_a]
chain_id = "picasso_kusama"
type = "picasso_kusama"
name = "picasso"
para_id = 2087
parachain_rpc_url = "" // need to host your own rpc node with unsafe flags turned on
relay_chain_rpc_url = "" // need to host your own rpc node with unsafe flags turned on
client_id = "10-grandpa-28"
connection_id = "connection-23"
channel_whitelist = [["channel-15", "transfer"]]
commitment_prefix = "0x6962632f"
private_key = ""
ss58_version = 49
key_type = "sr25519"
finality_protocol = "Grandpa"

[chain_b]
chain_id = "composable"
type = "composable"
name = "composable"
para_id = 2019
parachain_rpc_url = "" // need to host your own rpc node with unsafe flags turned on
relay_chain_rpc_url = "" // need to host your own rpc node with unsafe flags turned on
client_id = "10-grandpa-28"
connection_id = "connection-23"
channel_whitelist = [["channel-15", "transfer"]]
commitment_prefix = "0x6962632f"
private_key = ""
ss58_version = 50
key_type = "sr25519"
finality_protocol = "Grandpa"

[core]
```

We'd need to explain how to run the unsafe rpc nodes for the relaychain(s) and parachain(s)

Running hyperspace from docker:

```sh
docker run -d \
-e "RUST_LOG=hyperspace=trace,hyperspace_parachain=trace" \
-v <path-to-config>/config.toml:/config.toml composablefi/composable-centauri:latest \
relay \
--config /config.toml 
```
